### PR TITLE
ci-helper tests: only show the `console.log()` output upon failure

### PR DESCRIPTION
**Pull request by dscho**
This is much quieter and easier to parse.

### CODE REVIEW

**Comment by webstech** [comment]
I agree the output is excessive and have wanted to but not done anything about it.  I don't disagree with this change but would it be better to use a jest reporter to do it for everything?

I gave [jest-silent-reporter](https://github.com/rickhanlonii/jest-silent-reporter) a try and it was okay but it only prints the error.  OTOH, if you run the specific test, all the output is displayed so maybe that is acceptable.  Another alternative, JestReporterLogValidator  could be a generic model to use switches to control if output is printed regardless of test completion status.

I ran with this in the `package.json`.  It does not give the detail info on each test suite completion.
```
    "reporters": [
        "summary",
        [
            "jest-silent-reporter", { "showWarnings": true, "useDots": true }
        ]
    ]
```

**Comment by dscho** [comment]
Hmm. I actually like having the log shown explicitly. That opens the door for showing even more information _in the failure case only_, i.e. it equips us with more control.

**Comment by webstech** [comment]
> Hmm. I actually like having the log shown explicitly. That opens the door for showing even more information _in the failure case only_, i.e. it equips us with more control.

I'm not sure what you are saying in the first sentence.  This patch suppresses the log unless there is a failure so the log is not shown.  Sorry for my confusion.

Using a reporter will cover all tests (ie not just ci-helper).  It appears the output already goes through the default reporter so using a different reporter is not adding a layer.

**Review by webstech — APPROVED** [review]
The default reporter does not provide this and alternates are not providing what the default does provide, so lets go with this.

**Pull request merged**
