### PR TITLE
sous-chef/delete-test-branches: add missing semicolons

### PR DESCRIPTION
**Pull request by softworkz**

### CODE REVIEW

**Review by webstech — APPROVED** [review]
Thanks.  This is not the last of these.

**Comment by dscho** [comment]
> Thanks. This is not the last of these.

I wonder whether there is an ESLint rule we could use to auto-fix these issues?

**Comment by softworkz** [comment]
> Thanks. This is not the last of these.

These were in fact _all_ missing semicolons (R# has such checks).

**Comment by webstech** [comment]
> These were in fact _all_ missing semicolons (R# has such checks).

Turning on the `semi` rule in eslint reveals six more missing `;`.  I will open a PR to add the rule and update the files.

**Comment by softworkz** [comment]
Oh, sorry for misinformation, I'm curious where they are..

**Comment by webstech** [comment]
> Oh, sorry for misinformation, I'm curious where they are..

Sorry it was five (I had one in a file I was editing).  Please see first commit in PR #840.

**Pull request merged**
