### PR TITLE
build(deps): bump @octokit/rest from 18.6.0 to 18.6.6

### PR DESCRIPTION
**Pull request by webstech**
`cFile.data.commit.sha` can be undefined.  Not sure why it is now being detected as a problem. Adding code to basically ignore missing value for the test.

### CODE REVIEW

**Comment by webstech** [comment]
Will rebase after #622 and bump the version to 18.6.6 as per #621.

**Comment by dscho** [comment]
Hmm. https://docs.github.com/en/rest/reference/repos#create-or-update-file-contents says that `sha` is required. Maybe that's it?

**Comment by webstech** [comment]
> Hmm. https://docs.github.com/en/rest/reference/repos#create-or-update-file-contents says that `sha` is required. Maybe that's it?

The doc says it is required but the typings say otherwise.  `file-commit` in the typings shows most of the fields as optional.  That is probably wrong and not new so I may open an issue in [github/rest-api-description](https://github.com/github/rest-api-description).  We already have one issue open for a previous linting problem.  Not clear how a commit could have sha as an optional value when it is integral to the commit.

Still not sure what changed to allow the editors, etc. to find a type problem.

**Comment by webstech** [comment]
I found a closed [issue](https://github.com/github/rest-api-description/issues/107) that mentions `file-commit` and suggests it is fixed but it does not seem to be.

**Comment by dscho** [comment]
> I found a closed [issue](https://github.com/github/rest-api-description/issues/107) that mentions `file-commit` and suggests it is fixed but it does not seem to be.

That's too bad.

Let's merge this here PR for now.

**Review by dscho — APPROVED** [review]

**Pull request merged**
