### PR TITLE
getPRInfo change deprecated number to pull_number

### PR DESCRIPTION
**Pull request by webstech**
Change to get rid of the deprecated warning message in the log.

### CODE REVIEW

**Comment by webstech** [comment]
It appears this requires an 'npm update'.  I don't know when the name change was done (not going to track it down).  I did not catch what version of octokit/rest I had.  After doing an update it bumped to 16.28.2.  Is there a process for getting an update done in the test/prod environment (to pick up fixes)?

@dscho How do you want to handle this?

**Comment by dscho** [comment]
> @dscho How do you want to handle this?

I *think* you have to run `npm update octokit/rest` and then commit the `package-lock.json` file, but I am not really solid on npm usage...

**Comment by webstech** [comment]
Updated @octokit/rest in package.json to 16.25.0.  V16.24.1 deprecated 'number' from several requests.  This is messy in that 16.25.0 must be explicitly installed to get the package-lock.json to show it instead of a later release.  Unfortunately some other packages that got updated do reflect a later release than actually required by the dependencies of @octokit/rest.

Original problem was my (cough cough) npm was (cough cough) out of date.  Can get node (and yarn) updates through chocolatey but npm requires manual updates.

**Comment by dscho** [comment]
Thank you so much!

**Pull request merged**
