### PR TITLE
Add /cc command

### PR DESCRIPTION
**Pull request by webstech**
The value passed may be one or more email addresses.  The format is the same as for the cc: footer in the PR body.

### CODE REVIEW

**Review by dscho — CHANGES_REQUESTED** [review]
Very nice! Just one thing, we need to adjust the Azure Function, too: https://github.com/gitgitgadget/gitgitgadget/blob/b3ef98529be5bbd61ec4fb9ead26919316eec019/azure-function/index.js#L142

**Comment by webstech** [comment]
> Very nice! Just one thing, we need to adjust the Azure Function, too:

You had mentioned it and I still managed to miss it.  

Should the /cc command  be documented somewhere?

**Review by dscho — APPROVED** [review]

**Comment by dscho** [comment]
Thank you!

**Comment by dscho** [comment]
> Should the /cc command be documented somewhere?

Maybe ;-)

While we're thinking about `/cc`, I would also _love_ to have the option to, say, `/cc @webstech` (i.e. auto-map GitHub handles to email addresses, which might require having an internal map for users without public email addresses, or even https://github.com/gitgitgadget/gitgitgadget/issues/153 to be resolved)...

**Pull request merged**
